### ISSUE TITLE
一部の漢字が表示されない

### ISSUE THREAD

**Issue by maxasixi** [yuru7/NOTONOTO#1]
日本語で使用されている漢字が一部フォントファイルに含まれていないと思われます。
常用漢字内で自分が確認したものを以下に記しておきます。

衣羽雨音牙角穴月工示舟女小食斉舌走大肉八鼻父文麻羊

**Comment by yuru7** [comment]
ご報告ありがとうございます。
再現することを確認しました。

詳細な原因は追って調べますね。

**Comment by yuru7** [comment]
同じグリフが複数のコードポイントで参照されている場合に、参照が切れてしまう問題があったようです。

例: `衣 (U+8863)` の表示は、内部的には `⾐ (U+2F90)` のグリフを参照している。この不具合で、 `⾐ (U+2F90)` を参照している側のコードポイントで表示ができない

v0.0.3 で対処しました。お試しいただけると幸いです。
https://github.com/yuru7/NOTONOTO/releases/tag/v0.0.3

**Comment by maxasixi** [comment]
確認しました。迅速な対応ありがとうございました。
同じNoto系の等幅フォントであるNoto Sans Mono CJK JPは半角の字形が個人的に好みでないためNOTONOTOの存在はとても助かっています。
本issueはクローズさせていただきます。
